#!/bin/bash
title=nftables
description="- Includes a default firewall config"
status=on

main() {
    commandFailure="Configuring nftables firewall has failed."


    # Create table
    system "nft add table inet filter"

    # Input chain
    system "ufw default deny incoming &&
    ufw allow in on lo &&
    ufw deny in from 127.0.0.0/8 &&
    ufw deny in from ::1"

    # Output chain
    system "nft add chain inet filter output '{type filter hook output priority 0; policy accept;}'"

    # Forward chain 
    system "nft add chain inet filter forward '{type filter hook forward priority 0; policy drop;}'"

    # Save config
    commandFailure="Saving nftables config has failed." &&
        system "nft list ruleset >> /etc/nftables.conf"

    commandFailure="Enabling nftables has failed." &&
        system "ln -s /etc/sv/nftables /var/service"

    return 0
}
