#!/bin/bash

commandFailure="Base system installation has failed."

installSquashModule "01"
installSquashModule "02"

mkdir -p /mnt/tmp

commandFailure="Confuring fstab has failed."
partVar=$(blkid -o value -s UUID "$esp")
echo "UUID=$partVar /boot/efi vfat defaults 0 0" >> /mnt/etc/fstab || die

[ "$lvm" == "Yes" ] &&
    { echo "/dev/tridentu2/root / $filesystem defaults 0 0" >> /mnt/etc/fstab || die ; }

[ "$lvm" == "No" ] && [ "$encryption" == "Yes" ] && [ "$filesystem" != "btrfs" ] &&
    { partVar=$(blkid -o value -s UUID /dev/mapper/tridentu2) ; echo "UUID=$partVar / $filesystem defaults 0 0" >> /mnt/etc/fstab || die ; }

if [ "$filesystem" == "btrfs" ]; then
    case "$encryption" in
        Yes)
            partVar=$(blkid -o value -s UUID /dev/mapper/tridentu2)
            echo "UUID=$partVar / $filesystem $btrfsopts,subvol=@ 0 1" >> /mnt/etc/fstab || die

            [ "$createHome" == "Yes" ] &&
                { echo "UUID=$partVar /home $filesystem $btrfsopts,subvol=@home 0 2" >> /mnt/etc/fstab || die ; }

            echo "UUID=$partVar /.snapshots $filesystem $btrfsopts,subvol=@snapshots 0 2" >> /mnt/etc/fstab || die

            [ -n "$swapSize" ] && [ "$swapStyle" == "swapfile" ] &&
                { echo "UUID=$partVar /swap $filesystem rw,nodatacow,compress=none,subvol=@swap 0 0" >> /mnt/etc/fstab || die ; }

            echo "UUID=$partVar /var $filesystem $btrfsopts,nodatacow,subvol=@var 0 2" >> /mnt/etc/fstab || die
        ;;
        No)
            partVar=$(blkid -o value -s UUID "$root")
            echo "UUID=$partVar / $filesystem $btrfsopts,subvol=@ 0 1" >> /mnt/etc/fstab || die

            [ "$createHome" == "Yes" ] &&
                { echo "UUID=$partVar /home $filesystem $btrfsopts,subvol=@home 0 2" >> /mnt/etc/fstab || die ; }

            echo "UUID=$partVar /.snapshots $filesystem $btrfsopts,subvol=@snapshots 0 2" >> /mnt/etc/fstab || die

            [ -n "$swapSize" ] && [ "$swapStyle" == "swapfile" ] &&
                { echo "UUID=$partVar /swap $filesystem rw,nodatacow,compress=none,subvol=@swap 0 0" >> /mnt/etc/fstab || die ; }

            echo "UUID=$partVar /var $filesystem $btrfsopts,nodatacow,subvol=@var 0 2" >> /mnt/etc/fstab || die
        ;;
    esac
fi

[ "$lvm" == "No" ] && [ "$encryption" == "No" ] && [ "$filesystem" != "btrfs" ] &&
    { partVar=$(blkid -o value -s UUID "$root") ; echo "UUID=$partVar / $filesystem defaults 0 0" >> /mnt/etc/fstab || die ; }

[ -n "$swapSize" ] && [ "$swapStyle" == "partition" ] && [ "$lvm" == "Yes" ] &&
    { echo "/dev/tridentu2/swap swap swap defaults 0 0" >> /mnt/etc/fstab || die ; }

[ -n "$swapSize" ] && [ "$swapStyle" == "partition" ] && [ "$lvm" == "No" ] && 
    { partVar=$(blkid -o value -s UUID "$swap") ; echo "UUID=$partVar swap swap defaults 0 0" >> /mnt/etc/fstab || die ; }

[ -n "$swapSize" ] && [ "$swapStyle" == "swapfile" ] && [ "$filesystem" != "btrfs" ] &&
    { echo "/var/swapfile swap swap defaults 0 0" >> /mnt/etc/fstab || die ; }

[ -n "$swapSize" ] && [ "$swapStyle" == "swapfile" ] && [ "$filesystem" == "btrfs" ] &&
    { echo "/swap/swapfile none swap defaults 0 0" >> /mnt/etc/fstab || die ; }

[ "$separateHomePossible" != "No" ] && [ -n "$homeSize" ] && [ "$lvm" == "Yes" ] &&
    { echo "/dev/tridentu2/home /home $filesystem defaults 0 0" >> /mnt/etc/fstab || die ; }

[ -n "$homeSize" ] && [ "$lvm" == "No" ] && 
    { partVar=$(blkid -o value -s UUID "$home") ; echo "UUID=$partVar /home $filesystem defaults 0 0" >> /mnt/etc/fstab || die ; }

case "$bootloader" in
        uki)
            commandFailure="Configuring ukify kernel hook has failed."
            cp "$(pwd)/misc/60-ukify" /mnt/etc/kernel.d/post-install/60-ukify || die
            chmod 744 /mnt/etc/kernel.d/post-install/60-ukify || die

            commandFailure="Configuring uki base kernel parameters has failed."
            partVar=$(blkid -o value -s UUID "$root")
            [ "$lvm" == "Yes" ] && [ "$encryption" == "Yes" ] &&
                setKernelParam "rd.luks.uuid=$partVar root=/dev/tridentu2/root rootfstype=$filesystem rw"

            [ "$lvm" == "Yes" ] && [ "$encryption" == "No" ] &&
                setKernelParam "rd.lvm.vg=tridentu2 root=/dev/tridentu2/root rootfstype=$filesystem rw"

            if [ "$lvm" == "No" ] && [ "$encryption" == "No" ]; then
                setKernelParam "root=UUID=$partVar rootfstype=$filesystem rw"
            elif [ "$lvm" == "No" ] && [ "$encryption" == "Yes" ]; then
                setKernelParam "rd.luks.uuid=$partVar rd.luks.name=$partVar=tridentu2-root root=/dev/mapper/tridentu2-root rootfstype=$filesystem rw"
            fi

            [ "$filesystem" == "btrfs" ] &&
                setKernelParam "rootflags=subvol=@"
            ;;
        grub)
            commandFailure="Configuring grub base config has failed."
            if [ "$encryption" == "Yes" ]; then
                partVar=$(blkid -o value -s UUID "$root")
                [ "$lvm" == "Yes" ] &&
                    setKernelParam "rd.lvm.vg=tridentu2 rd.luks.uuid=$partVar"

                [ "$lvm" == "No" ] &&
                    setKernelParam "rd.luks.uuid=$partVar"

                echo "GRUB_ENABLE_CRYPTODISK=y" >> /mnt/etc/default/grub || die

                echo "tridentu2   UUID=$partVar   /boot/volume.key   luks" >> /mnt/etc/crypttab || die
                echo 'install_items+=" /boot/volume.key /etc/crypttab "' >> /mnt/etc/dracut.conf.d/10-crypt.conf || die
            fi
            ;;
    esac

    [ "$initrdhostonly" == "true" ] &&
        { echo 'hostonly="yes"' >> /mnt/etc/dracut.conf || die ; }

[ "$acpi" == "false" ] &&
    { commandFailure="Disabling acpi has failed." ; setKernelParam "acpi=off" ; }

[ "$intel_pstate" == "false" ] &&
    { commandFailure="Disabling intel_pstate has failed." ; setKernelParam "intel_pstate=disable" ; }

if [ "$libc" == "glibc" ]; then
    commandFailure="Locale configuration has failed."
    echo "$locale" > /mnt/etc/locale.conf || die
    echo "$libclocale" >> /mnt/etc/default/libc-locales || die
fi

echo "$hostname" > /mnt/etc/hostname ||
    { commandFailure="Hostname configuration has failed." ; die ; }

# Configure non-partition methods of swapping
# I feel like this isn't really the place for this-
# but neither is setup-disk or otherwise really, so:
case "$swapStyle" in
    zram)
        commandFailure="Configuring zram has failed."
        echo "zram" >> /mnt/etc/modules-load.d/zram.conf || die
    ;;
    swapfile)
        if [ "$filesystem" != "btrfs" ]; then
            commandFailure="Configuring swapfile has failed."
            swapSize=$(echo "$swapSize" | sed 's/G//g')
            echo "Creating swapfile..."
            dd if=/dev/zero of=/mnt/var/swapfile bs=1024M count="$swapSize" status=progress || die
            chmod 600 /mnt/var/swapfile || die # root only.
            mkswap /mnt/var/swapfile || die
        else
            btrfs filesystem mkswapfile --size "$swapSize" --uuid clear /mnt/swap/swapfile || die
            swapon /mnt/swap/swapfile || die
        fi
    ;;
esac

return 0
