#!/bin/bash

# Source installer library
. "/tmp/libtridentuis" ||
    { echo "/tmp/libtridentuis not found. Cannot continue." ; exit 1 ; }

. "/tmp/installerOptions" ||
    { commandFailure="Sourcing installer variable file on the new system has failed." ; die ; }

exitFunction () {

    
    if [ "$bootloader" == "uki" ]; then
        # For one reason or another, some systems seem to remove our entry without setting it as next to boot.
        commandFailure="Setting default boot entry has failed."
        bootEntry=$(efibootmgr --unicode | grep "Tridentu 2" | while read c1 c2; do echo $c1; done | sed 's/Boot//g' | sed 's/*//g') || die
        efibootmgr --bootorder $bootEntry || die
    fi

    exit 0
}

userPassword() {
    echo -e "${YELLOW}Set the password for the user $username: ${NC}"

    while : ; do
        passwd "$username"
        [ "$?" -eq 0 ] && break
    done

    exitFunction
}

rootPassword() {
    echo -e "${YELLOW}Set your root password: ${NC}"

    while : ; do
        passwd root
        [ "$?" -eq 0 ] && break
    done

    [ -n "$username" ] &&
        userPassword

    exitFunction
}

commandFailure="Setting root directory permissions has failed."
chown root:root / || die
chmod 755 / || die


[ "$encryption" == "Yes" ] &&
        commandFailure="Configuring LUKS key has failed."

        echo -e "Configuring LUKS key... \n"
        dd bs=1 count=64 if=/dev/urandom of=/boot/volume.key || die
        echo -e "${YELLOW}Enter your encryption passphrase: ${NC}\n"
        cryptsetup luksAddKey "$root" /boot/volume.key || die
        chmod 000 /boot/volume.key || die
        chmod -R g-rwx,o-rwx /boot || die

case "$bootloader" in
    grub)
        build-grub ||
            { commandFailure="GRUB installation has failed." ; die ; }
    ;;
esac

ln -sf /usr/share/zoneinfo/"$timezone" /etc/localtime ||
    { commandFailure="Setting timezone has failed." ; die ; }


if [ -z "$username" ]; then
    clear
    rootPassword
else
    commandFailure="Creating user has failed."
    useradd "$username" -m -d /home/"$username" || die
    usermod -aG audio,video,kvm,netdev "$username" || die
    clear
    echo -ne "Should user "$username" be a superuser? (y/n) "
    read superPrompt

    if [ $superPrompt == "y" ] || [ $superPrompt == "Y" ]; then
        usermod -aG wheel "$username" || die
        sed -i -e 's/# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/g' /etc/sudoers || die
    fi

    clear
    rootPassword
fi
